### ISSUE TITLE
Mean and std for normalization?

### ISSUE THREAD

**Issue by SunDoge** [kylemin/S3D#4]
Thanks for your implementation! 
Would you mind sharing your mean and std for video normalization for training process?  In `main.py` you use 0.5, is it the same in training?

**Comment by kylemin** [comment]
Hi,
Thank you for your interest.
Yes, following [the I3D convention](https://github.com/deepmind/kinetics-i3d), pixel values are rescaled to [-1, 1] in both training and testing, so you can just use the [`transform` function](https://github.com/kylemin/S3D/blob/master/main.py#L63).

**Comment by SunDoge** [comment]
I see. Thx.
